#!/bin/bash

template=$1
items=$2
files=$3
output=$4
echo "Generating page from template $template using files in $files, outputting to $output"
rm -f "$output"

# Extract repeat blocks from template
score_block=$(awk '/<!-- BEGIN:SCORE -->/,/<!-- END:SCORE -->/' $1)
header_block=$(awk '/<!-- BEGIN:HEADER -->/,/<!-- END:HEADER -->/' $1)

# Start writing the final HTML (everything before the repeat block)
awk '/<!-- BEGIN:HEADER -->/ {exit} {print}' "$template" > "$output"

# Generate and insert one block per file
for item in $items; do
    if [[ $item == *.mscx ]]
    then
        fname="${item##*/}"
        title="${fname%.*}"
        source=$(grep '<metaTag name="source">' "$item" | sed -n 's/.*<metaTag name="source">\([^<]*\)<\/metaTag>.*/\1/p')
        source=$(echo "$source" | sed 's/ .*//g') # TODO: support multiple sources
        echo "$title – $source"

        block="$score_block"
        block=${block//\{\{TITLE\}\}/"$title"}
        block=${block//\{\{SOURCE\}\}/"$source"}

        echo "$block" >> "$output"
    else
        id="$item"
        title=$(echo "$id" | sed 's/_/ /g')
        echo "HEADER $item $title"

        block="$header_block"
        block=${block//\{\{ID\}\}/"$id"}
        block=${block//\{\{TITLE\}\}/"$title"}

        echo "$block" >> "$output"
    fi
done

# Finish writing the HTML (everything after the repeat block)
awk '/<!-- END:SCORE -->/ {found=1; next} found' $1 >> "$output"
 
